export const AUDIO_CONFIG = {
  SAMPLE_RATE: 16000,
  RECORDING_DURATION: 3,
  CHANNEL_COUNT: 1,
  SAMPLE_SIZE: 16,
  API_TIMEOUT: 30000,
};

export const AUDIO_FORMAT = {
  NUM_CHANNELS: 1,
  FORMAT: 1, // PCM
  BIT_DEPTH: 16,
};
